- name: create ec2 and R53 records
  hosts: all
  connection: local
  vars:
    sg_id: "sg-00d129afc92780fa5"
    ami_id: "ami-0220d79f3f480ecf5"
    envir:  dev
    domain_name: "daws88sraga.online"
    instances:
    - mongodb
    - catalogue
  tasks:  
  - name:  create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"      
      region: us-east-1
      name: "{{ item }}-{{ envir }}"
      tags:
        Project:  "roboshop"
        Component:  "{{ item }}"
        Environment: "{{ envir }}"
        Name: "{{ item }}-{{ envir }}"
    loop: "{{ instances }}"
    register: ec2_output
  
  - name: print ec2-output
    ansible.builtin.debug:  
      msg: "{{ ec2_output }}"

- name: Create R53 record for instance
  amazon.aws.route53:
    state: present
    zone: "{{ domain_name }}" #daws88sraga.online"
    record: "{{ item.item }}-{{ envir }}-{{ domain_name }}"   #mongodb-dev.daws88sraga.online #frontend-dev.daws88sraga.online
    type: A
    ttl: 1
    value: "{{ item.instances[0].private_ip_address }}"
    wait: true
  loop: "{{ ec2-output.results }}"  # need to search in this list

- name: Create R53 record for instance
  amazon.aws.route53:
    state: present
    zone: "{{ domain_name }}" #daws88sraga.online"
    record: "roboshop-{{ envir }}-{{ domain_name }}"   #roboshop-dev.daws88sraga.online
    type: A
    ttl: 1
    value: "{{ item.instances[0].public_ip_address }}"
    wait: true    
  loop: "{{ ec2-output.results }}"  # need to search in this list  
  when: item.item == "frontend"